### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by J1Yeon-Kim** [lijiaman/chois_release#1]
Thanks for the great work!
I'm trying to test your demo code, but it says there is some missing data.
How can I get "left/right hand vids.npy" from the code?

> FileNotFoundError: [Errno 2] No such file or directory: 'data/part_vert_ids/left_hand_vids.npy'

**Comment by lijiaman** [comment]
Thanks for testing the demo code! I just uploaded the folder here https://github.com/lijiaman/chois_release/tree/main/data/part_vert_ids

**Comment by J1Yeon-Kim** [comment]
Thanks a lot!
But some errors still occur when loading object_bps.npy file.
Could you please check it again? 

> FileNotFoundError: [Errno 2] No such file or directory: '/processed_data/cano_object_bps_npy_files_for_test_joints24_120/sub16_clothesstand_000_0.npy'

**Comment by lijiaman** [comment]
You need to download processed_data first, and run the code to generate this folder cano_object_bps_npy_files_for_test_joints24_120. Please check "Prerequisites" section.

**Comment by hars-singh** [comment]
Hi @lijiaman Thanks for the great work!!

I have also encountered the same error. I have downloaded the dataset and generated this folder but the files are not inside this. Error logs:

Exception has occurred: FileNotFoundError
Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/harsh/Documents/chois_release/manip/data/cano_traj_dataset.py", line 875, in __getitem__
    obj_bps_data = np.load(obj_bps_npy_path) # T X N X 3
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/harsh/Documents/chois_release/processed_data/cano_object_bps_npy_files_for_test_joints24_120/sub16_clothesstand_000_0.npy'
  File "/home/harsh/Documents/chois_release/trainer_chois.py", line 1069, in cond_sample_res
    for s_idx, val_data_dict in enumerate(test_loader):
  File "/home/harsh/Documents/chois_release/trainer_chois.py", line 3109, in run_sample
    trainer.cond_sample_res()
  File "/home/harsh/Documents/chois_release/trainer_chois.py", line 3190, in <module>
    run_sample(opt, device)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/harsh/Documents/chois_release/manip/data/cano_traj_dataset.py", line 875, in __getitem__
    obj_bps_data = np.load(obj_bps_npy_path) # T X N X 3
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/harsh/Documents/chois_release/processed_data/cano_object_bps_npy_files_for_test_joints24_120/sub16_clothesstand_000_0.npy'

**Comment by lijiaman** [comment]
Hi, please run the training script first to generate all the processed bps files.

**Comment by hars-singh** [comment]
Hi, When I am running training script then I am getting this. 

(chois_env) (base) harsh@harsh-system:~/Documents/chois_release$ sh scripts/train_chois.sh
tensor(1.0000, dtype=torch.float64) tensor(1.0000, dtype=torch.float64) tensor(0.0064, dtype=torch.float64)
Total number of windows for training:28859
Total number of windows for validation:482
Traceback (most recent call last):
  File "trainer_chois.py", line 3192, in <module>
    run_train(opt, device)
  File "trainer_chois.py", line 3065, in run_train
    trainer.train()
  File "trainer_chois.py", line 467, in train
    data_dict = next(self.dl)
  File "trainer_chois.py", line 168, in cycle
    for data in dl:
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/harsh/Documents/chois_release/manip/data/cano_traj_dataset.py", line 875, in __getitem__
    obj_bps_data = np.load(obj_bps_npy_path) # T X N X 3
  File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/harsh/Documents/chois_release/processed_data/cano_object_bps_npy_files_joints24_120/sub15_trashcan_037_12137.npy'

**Comment by snorfyang** [comment]
> Hi, When I am running training script then I am getting this.
> 
> (chois_env) (base) harsh@harsh-system:~/Documents/chois_release$ sh scripts/train_chois.sh tensor(1.0000, dtype=torch.float64) tensor(1.0000, dtype=torch.float64) tensor(0.0064, dtype=torch.float64) Total number of windows for training:28859 Total number of windows for validation:482 Traceback (most recent call last): File "trainer_chois.py", line 3192, in run_train(opt, device) File "trainer_chois.py", line 3065, in run_train trainer.train() File "trainer_chois.py", line 467, in train data_dict = next(self.dl) File "trainer_chois.py", line 168, in cycle for data in dl: File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in **next** data = self._next_data() File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data return self._process_data(data) File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data data.reraise() File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise raise exception FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/harsh/Documents/chois_release/manip/data/cano_traj_dataset.py", line 875, in **getitem** obj_bps_data = np.load(obj_bps_npy_path) # T X N X 3 File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: '/home/harsh/Documents/chois_release/processed_data/cano_object_bps_npy_files_joints24_120/sub15_trashcan_037_12137.npy'

same problem here

**Comment by cutepiggy123** [comment]
Hi anyone know how to fix this

> Hi, When I am running training script then I am getting this.
> 
> (chois_env) (base) harsh@harsh-system:~/Documents/chois_release$ sh scripts/train_chois.sh tensor(1.0000, dtype=torch.float64) tensor(1.0000, dtype=torch.float64) tensor(0.0064, dtype=torch.float64) Total number of windows for training:28859 Total number of windows for validation:482 Traceback (most recent call last): File "trainer_chois.py", line 3192, in run_train(opt, device) File "trainer_chois.py", line 3065, in run_train trainer.train() File "trainer_chois.py", line 467, in train data_dict = next(self.dl) File "trainer_chois.py", line 168, in cycle for data in dl: File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in **next** data = self._next_data() File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data return self._process_data(data) File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data data.reraise() File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise raise exception FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/harsh/Documents/chois_release/manip/data/cano_traj_dataset.py", line 875, in **getitem** obj_bps_data = np.load(obj_bps_npy_path) # T X N X 3 File "/home/harsh/miniconda3/envs/chois_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: '/home/harsh/Documents/chois_release/processed_data/cano_object_bps_npy_files_joints24_120/sub15_trashcan_037_12137.npy'
