### ISSUE TITLE
Missing Data when generating scene-aware long sequence

### ISSUE THREAD

**Issue by yw0208** [lijiaman/chois_release#3]
Hi,
When I run
```
sh scripts/test_chois_long_seq_in_scene.sh
```
there are some FileNotFoundError. I have checked codes, and I believe there are three missing files at least.
<img width="443" alt="image" src="https://github.com/user-attachments/assets/9c9979a2-20a6-46d3-9f6c-0fdfb6015e33">
They should be essential to reproduce this work.
Thank you.

**Comment by lijiaman** [comment]
I uploaded some .json files in create_eval_dataset/. Please check. Also, to generate new scene-aware paths in Habitat, you could check https://github.com/lijiaman/chois_release/blob/main/utils/create_eval_dataset/create_eval_data.py
