### ISSUE TITLE
processed_data 不全

### ISSUE THREAD

**Issue by OwenCaleb** [lijiaman/chois_release#4]
FileNotFoundError: [Errno 2] No such file or directory: './processed_data/cano_object_bps_npy_files_joints24_120/sub15_trashcan_037_12137.npy'

**Comment by lijiaman** [comment]
Hi, this data can be generated by running the training script.

**Comment by ueta-takeo** [comment]
@lijiaman 
Thank you for the great work!

In the Prerequisites, it says to download processed_data, but it contains the following files:

・cano_train_diffusion_manip_window_120_joints24.p
・cano_test_diffusion_manip_window_120_joints24.p

The npy file seems to be created by the **self.cal_normalize_data_input()** method in the constructor of the **CanoObjectTrajDataset** class, but if the above files exist, it seems that the else branch below will not be entered.

```
if os.path.exists(processed_data_path):
            self.window_data_dict = joblib.load(processed_data_path)

            # if not self.train:
                # Mannually enable this. For testing data (discarded some testing sequences)
                # self.get_bps_from_window_data_dict()
        else:
            self.data_dict = joblib.load(seq_data_path)

            self.extract_rest_pose_object_geometry_and_rotation()

            self.cal_normalize_data_input()
            joblib.dump(self.window_data_dict, processed_data_path)
```
